name: Simple Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - run: go run hello.go
