name: Simple Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: run go
        run: go run hello.go

      - name: build go
        run: go build hello.go

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set Test
        id: set-test-stage
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}