name: Simple Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: run go
        run: go run hello.go

      - name: build go
        run: go build -o build/hello hello.go

      - name: Upload Go binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary
          path: build/hello

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set Test
        id: set-test-stage
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  dev:
    name: Dev
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set Dev
        id: set-dev-stage
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}